Tharshana
batch5-defecttracker/defect-tracker-back-end pull request #49
Opened 2021-03-09 12:04 UTC by stharshana

2021-03-09 14:10 UTC, raj-mirabilis commented
Please resolve the Conflicts in the Constants - EndpointURI, SubModuleDTO and ProjectSerImpl

2021-03-09 14:11 UTC, raj-mirabilis commented on defect-tracker-data-common/src/main/java/com/defect/tracker/data/dto/SubModuleDto.java
> -	private Long subModId;
consider the ID - naming convention

2021-03-09 14:12 UTC, raj-mirabilis commented on defect-tracker-server/src/main/java/com/defect/tracker/util/Constants.java
> -
remove the unwanted spaces

2021-03-09 14:13 UTC, raj-mirabilis commented on defect-tracker-server/src/main/resources/application-dev.properties
> -spring.datasource.password=root
please consider the application-dev properties - when adding and pushing

2021-03-09 14:13 UTC, raj-mirabilis commented on defect-tracker-data-common/src/main/java/com/defect/tracker/data/dto/SubModuleDto.java
getter and setters

2021-03-09 14:14 UTC, raj-mirabilis requested changes
please the consider the corrections

2021-03-09 16:16 UTC, ramz7 commented on defect-tracker-server/src/main/java/com/defect/tracker/controller/SubModuleController.java
> +		 * ValidationFailureResponse(ValidationConstance.SUBMODULE_NOT_EXIST,
remove this commented code

2021-03-09 16:17 UTC, ramz7 commented on defect-tracker-server/src/main/java/com/defect/tracker/services/DesignationServiceImpl.java
> +
remove line break

2021-03-09 16:17 UTC, ramz7 commented on defect-tracker-server/src/main/java/com/defect/tracker/services/ProjectSerImple.java
> +		// TODO Auto-generated method stub
why this unimplemented method?

2021-03-10 05:34 UTC, stharshana commented on defect-tracker-server/src/main/java/com/defect/tracker/services/ProjectSerImple.java
> +		// TODO Auto-generated method stub
@Kajanthuka

2021-03-10 06:35 UTC, stharshana commented on defect-tracker-server/src/main/resources/application-dev.properties
> -spring.datasource.password=root
ok I considered

2021-03-10 11:49 UTC, merged

2021-03-10 15:27 UTC, Kajanthuka commented
This Service file might be deleted, In Action Have Another Service file  Exist => Name with ProjectServiceImpl,